### ISSUE TITLE
Normals Orientation

### ISSUE THREAD

**Issue by dmerziii** [BorisTheBrave/blue-noise-particles#1]
I am experiencing an interesting issue with the normals being generated. I would like the normals to be oriented the same as my original mesh. However, I've found that the normals are all turning slightly upward. This is making my objects rotate/orient unexpectedly when modifying the particle settings.

**Comment by dmerziii** [comment]
I have come up with a round-about solution. I am using a point cloud skinner to take the points and turn into a mesh, from there the normals seem to orient themselves properly, or at least similar to the original mesh.

**Comment by BorisTheBrave** [comment]
Unfortunately blender's API doesn't let me directly edit particles, nor assign normals to vertices. So the best I can offer you is this fix that generates tiny faces with the normals oriented correctly.
