### ISSUE TITLE
When I try to run Poisson Sampling, Blender returns the following error:

### ISSUE THREAD

**Issue by theoldben** [BorisTheBrave/blue-noise-particles#2]
line 372, in execute locations, normals, densities = particle_distribute(obj, initial_particle_count, self.emit_from, scene)
line 173, in particle_distribute scene.update()
AttributeError: 'Scene' object has no attribute 'update'

**Comment by BorisTheBrave** [comment]
What version of blender are you using, and what version of the script?

**Comment by theoldben** [comment]
I have the 1.0.0 version of the script and I am on the 2.80.74 build from 18.06.2019

**Comment by theoldben** [comment]
I fixed it. Will add pull request.
