### ISSUE TITLE
Add on installed and enabled but not working

### ISSUE THREAD

**Issue by Jafferman** [BorisTheBrave/blue-noise-particles#4]
Hey Boris,
I am currently using blender version 2.92 and am having trouble getting your add on to work, I have successfully installed it and enabled it, however it appears greyed out in the mesh menu. When hovering over the text I get a caption which says undocumented operator and was hoping you could help me.

**Comment by BorisTheBrave** [comment]
I think you need a mesh selected.

**Comment by Jafferman** [comment]
![2021-06-04](https://user-images.githubusercontent.com/85321360/120804907-11f6dc80-c53d-11eb-9910-1a69bf9c6c8e.png)
I have this issue even with the mesh selected as shown in the screenshot.

**Comment by BorisTheBrave** [comment]
Not sure then. I may try the plugin on 2.93 later and see, but no promises.

**Comment by Jafferman** [comment]
Ok, thanks for getting back to me.

**Comment by BorisTheBrave** [comment]
I've tried in 2.93 and it worked fine for me. I'm afraid I cannot help you further.
